name: ExperimentalRunnerNba

on:
  push:
    branches:
      - feature/*  # Triggered on any branch starting with 'feature/'
  workflow_dispatch:   # Allow manual triggering and custom parameters
    inputs:
      branch:
        description: 'Branch to deploy'  # Custom input to specify a branch
        required: false  # Optional, set to true if you want this to be required
        default: ${{ github.ref }}  # Default to the branch that triggered the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GSHEET_NBA_MAKU_CREDENTIALS: ${{ secrets.GSHEET_NBA_MAKU_CREDENTIALS }}
      GSHEET_NBA_MAKU_FOLDER_ID: ${{ secrets.GSHEET_NBA_MAKU_FOLDER_ID }}
      FORMAT_OUTPUT_TYPE: ${{ vars.FORMAT_OUTPUT_TYPE }}
      FILENAME_OUTPUT: ${{ vars.FILENAME_OUTPUT }}
      GSHEET_NBA_MAKU_TIME_DELAY: ${{ vars.GSHEET_NBA_MAKU_TIME_DELAY }}
      ONEDRIVE_EXCEL_NBA_PATH: ${{ vars.ONEDRIVE_EXCEL_NBA_PATH }}
      LOCAL_EXCEL_NBA_PATH: ${{ vars.LOCAL_EXCEL_NBA_PATH }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

      # Debugging step to verify that the SSH key is loaded into the ssh-agent
      - name: Debug SSH private key
        run: |
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" | ssh-add -
          ssh-add -l  # List all the loaded SSH keys

          - name: SSH into Google Cloud VM and Deploy
          run: |
            # Use the branch from the 'workflow_dispatch' input or default to the one that triggered the push event
            BRANCH_NAME="${{ github.event.inputs.branch || github.ref }}"
            
            # Strip the 'refs/heads/' prefix to get the actual branch name
            BRANCH_NAME=${BRANCH_NAME#refs/heads/}
            
            echo "Deploying branch: $BRANCH_NAME"
        
            ssh -o StrictHostKeyChecking=no github-actions@34.83.36.54 << EOF
              # Check if Python is installed
              if ! command -v python3 &>/dev/null; then
                echo "Python3 is not installed. Installing Python3..."
                sudo apt-get update
                sudo apt-get install -y python3 python3-pip python3-venv
              else
                echo "Python3 is already installed."
              fi
        
              # Navigate to the repository
              cd /home/github-actions/NbaStats
        
              # Fetch all branches to ensure we have the latest references
              git fetch --all
        
              # Check if the branch exists locally, and switch to it or create it
              if git rev-parse --verify $BRANCH_NAME > /dev/null 2>&1; then
                git checkout $BRANCH_NAME
              else
                git checkout -b $BRANCH_NAME origin/$BRANCH_NAME
              fi
        
              # Pull the latest changes for the branch
              git pull origin $BRANCH_NAME
        
              # Set up Python environment
              python3 -m venv venv
              source venv/bin/activate
        
              # Install dependencies
              pip install --upgrade pip
              pip install -r requirements.txt
        
              # Run the Python script
              python3 poc.py
            EOF
        





# name: ExperimentalRunnerNba

# on:
#   push:
#     branches:
#       - feature/*

# jobs:
#   your_job_name:
#     runs-on: self-hosted

#     env:
#       GSHEET_NBA_MAKU_CREDENTIALS: ${{ secrets.GSHEET_NBA_MAKU_CREDENTIALS }}
#       GSHEET_NBA_MAKU_FOLDER_ID: ${{ secrets.GSHEET_NBA_MAKU_FOLDER_ID }}
#       FORMAT_OUTPUT_TYPE: ${{ vars.FORMAT_OUTPUT_TYPE }}
#       FILENAME_OUTPUT: ${{ vars.FILENAME_OUTPUT }}
#       GSHEET_NBA_MAKU_TIME_DELAY: ${{ vars.GSHEET_NBA_MAKU_TIME_DELAY }}
#       ONEDRIVE_EXCEL_NBA_PATH: ${{ vars.ONEDRIVE_EXCEL_NBA_PATH }}
#       LOCAL_EXCEL_NBA_PATH: ${{ vars.LOCAL_EXCEL_NBA_PATH }}

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Set Up Python 3.9
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.9

#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run Your Script
#         run: |
#           python GetAndBulkDataFromNbaPage.py
